on: [push]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw clean package 
          -Dquarkus.container-image.build=true 
          -Dnative 
          -Dquarkus.native.container-build=true 
          -Dquarkus.container-image.username=${{ secrets.DOCKER_USERNAME }} 
          -Dquarkus.container-image.password=${{ secrets.DOCKER_PASSWORD }} 
          -Dquarkus.container-image.push=true 
